#!/usr/bin/env bash
#
# update-index.sh — Regenerate docs/adr/index.md from ADR files
#
# Usage: bash update-index.sh [project-root]
#   project-root: defaults to current directory
#
# This script:
# 1. Scans docs/adr/*.md (excluding index.md)
# 2. Extracts title, status, and keywords from each ADR
# 3. Regenerates docs/adr/index.md with a complete table
# 4. Reports any ADRs with missing required fields

set -euo pipefail

PROJECT_ROOT="${1:-.}"
ADR_DIR="$PROJECT_ROOT/docs/adr"
INDEX_FILE="$ADR_DIR/index.md"

if [[ ! -d "$ADR_DIR" ]]; then
  echo "Error: $ADR_DIR does not exist"
  echo "Create it with: mkdir -p $ADR_DIR"
  exit 1
fi

# Collect ADR data
declare -a ADR_NUMBERS=()
declare -a ADR_TITLES=()
declare -a ADR_STATUSES=()
declare -a ADR_KEYWORDS=()
declare -a WARNINGS=()

for adr_file in "$ADR_DIR"/[0-9]*.md; do
  [[ -f "$adr_file" ]] || continue

  filename=$(basename "$adr_file")
  
  # Extract number from filename (e.g., 001 from 001-auth-jwt.md)
  number=$(echo "$filename" | grep -oP '^\d+' || echo "")
  if [[ -z "$number" ]]; then
    WARNINGS+=("$filename: no number in filename")
    continue
  fi

  # Extract title from first H1 line: # ADR-NNN: Title
  title=$(grep -m1 '^# ADR-' "$adr_file" | sed 's/^# ADR-[0-9]*: //' || echo "")
  if [[ -z "$title" ]]; then
    # Fallback: try first H1 without ADR- prefix
    title=$(grep -m1 '^# ' "$adr_file" | sed 's/^# //' || echo "Untitled")
    WARNINGS+=("$filename: title doesn't follow 'ADR-NNN: Title' format")
  fi

  # Extract status from ## Status section
  status=$(awk '/^## Status/{found=1; next} found && /^[A-Z]/{print; exit}' "$adr_file" | tr -d '{}' | xargs || echo "")
  if [[ -z "$status" ]]; then
    status="Unknown"
    WARNINGS+=("$filename: missing or empty Status field")
  fi

  # Extract keywords from the Keywords line at the bottom
  keywords=$(grep -i '^\*\*Keywords\*\*:' "$adr_file" | sed 's/^\*\*Keywords\*\*:\s*//' | xargs || echo "")
  if [[ -z "$keywords" ]]; then
    keywords="—"
    WARNINGS+=("$filename: missing Keywords field")
  fi

  ADR_NUMBERS+=("$number")
  ADR_TITLES+=("$title")
  ADR_STATUSES+=("$status")
  ADR_KEYWORDS+=("$keywords")
done

# Sort by number
IFS=$'\n' sorted_indices=($(for i in "${!ADR_NUMBERS[@]}"; do echo "$i ${ADR_NUMBERS[$i]}"; done | sort -k2 -n | awk '{print $1}'))
unset IFS

# Generate index.md
{
  echo "# ADR Index"
  echo ""
  echo "Architecture Decision Records for this project."
  echo ""
  echo "| # | Title | Status | Keywords |"
  echo "|---|-------|--------|----------|"

  for i in "${sorted_indices[@]}"; do
    num="${ADR_NUMBERS[$i]}"
    title="${ADR_TITLES[$i]}"
    status="${ADR_STATUSES[$i]}"
    keywords="${ADR_KEYWORDS[$i]}"
    
    # Find the actual filename for the link
    adr_file=$(ls "$ADR_DIR"/${num}-*.md 2>/dev/null | head -1)
    if [[ -n "$adr_file" ]]; then
      link_file=$(basename "$adr_file")
      echo "| $num | [$title](./$link_file) | $status | $keywords |"
    else
      echo "| $num | $title | $status | $keywords |"
    fi
  done

  echo ""
  echo "---"
  echo ""
  echo "*Auto-generated by update-index.sh on $(date +%Y-%m-%d). Do not edit manually.*"
} > "$INDEX_FILE"

echo "Index regenerated: $INDEX_FILE"
echo "  Total ADRs: ${#ADR_NUMBERS[@]}"

if [[ ${#WARNINGS[@]} -gt 0 ]]; then
  echo ""
  echo "Warnings:"
  for warning in "${WARNINGS[@]}"; do
    echo "  - $warning"
  done
fi
